apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dtc.fullname" . }}
  labels:
    {{- include "dtc.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "dtc.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "dtc.fullname" . }}
        {{- include "dtc.labels" . | nindent 8 }}
    spec:
      {{- if .Values.app.imagePullSecrets }}
      imagePullSecrets:
        {{- range .Values.app.imagePullSecrets }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
      containers:
        - name: app
          image: "{{ required "app.image.repository is required" .Values.app.image.repository }}:{{ required "app.image.tag is required" .Values.app.image.tag }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.app.containerPort }}

          {{- $cm := .Values.app.configMap | default dict }}
          {{- $cmdata := $cm.data | default dict }}
          {{- $s := .Values.app.secret | default dict }}
          {{- $sdata := $s.stringData | default dict }}

          {{- if or (and $cm.enabled (gt (len $cmdata) 0)) (and $s.enabled (gt (len $sdata) 0)) }}
          envFrom:
            {{- if and $cm.enabled (gt (len $cmdata) 0) }}
            - configMapRef:
                name: {{ include "dtc.fullname" . }}-config
            {{- end }}
            {{- if and $s.enabled (gt (len $sdata) 0) }}
            - secretRef:
                name: {{ include "dtc.fullname" . }}-secret
            {{- end }}
          {{- end }}

          {{- if .Values.app.env }}
          env:
            {{- range $key, $value := .Values.app.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}

          startupProbe:
            httpGet:
              path: /
              port: {{ .Values.app.containerPort }}
            periodSeconds: 2
            timeoutSeconds: 2
            failureThreshold: 45

          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.app.containerPort }}
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 12

          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.app.containerPort }}
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 6
