{{- $s := .Values.app.secret | default dict }}
{{- $sd := $s.stringData | default dict }}
{{- if and ($s.enabled) (gt (len $sd) 0) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dtc.fullname" . }}-secret
type: Opaque
stringData:
{{- range $k, $v := $sd }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
{{- end }}
